export const repositoryMethods = Object.freeze([
  'getCurrentRunGroup',
  'listAnalysisRuns',
  'getBrief',
  'listPatterns',
  'getPattern',
  'listHotspots',
  'listAnomalies',
  'getAreaRisk',
  'getNetwork',
  'getDistrictContext',
  'listReports',
  'getReport',
  'createReport',
  'updateReport',
  'deleteReport',
  'isReportReferenced',
  'listDashboards',
  'getDashboard',
  'createDashboard',
  'updateDashboard',
  'deleteDashboard',
  'listDashboardItems',
  'createDashboardItem',
  'updateDashboardItem',
  'deleteDashboardItem',
  'replaceDashboardItems',
  'listContentShares',
  'createContentShare',
  'deleteContentShare',
  'getUserPreference',
  'upsertUserPreference',
  'getAccessProfile',
  'getUnits',
  'getAlert',
  'listAlerts',
  'createCommand',
  'getCommand',
  'getCommandByIdempotencyHash',
  'updateCommand',
  'insertDomainArtifact',
  'findDomainArtifactByCommand',
  'getAssignmentsForAlert',
  'getAssignmentsForEmployee',
  'compareAndSwapAlert',
  'appendAuditEvent',
  'findAuditByCommand',
  'getAuditStream',
  'reconcileCommand',
  'listCommands',
  'listAuditEvents',
  'persistValidatedSource',
  'getValidatedSource',
  'getRefreshBatch',
  'createRefreshBatch',
  'updateRefreshBatch',
  'publishRefreshBatch',
]);

export function assertRepository(repository) {
  for (const method of repositoryMethods) {
    if (typeof repository?.[method] !== 'function') throw new TypeError(`repository missing ${method}`);
  }
  return repository;
}
