import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, expect, test, vi } from 'vitest';
import { Boxes } from 'lucide-react';
import { MemoryRouter } from 'react-router-dom';
import { BrandProvider } from '../../branding/BrandProvider.jsx';
import { CommandCenterShell } from './CommandCenterShell.jsx';
import { commandCenterDestinations } from './command-center-navigation.js';
afterEach(() => { cleanup(); localStorage.clear(); });
const renderShell = props => render(<MemoryRouter><BrandProvider><CommandCenterShell {...props} /></BrandProvider></MemoryRouter>);
test('loads an honest empty landing dashboard', async () => { const api = { get: vi.fn(async () => ({ data: { id: 'D-1', name: 'State overview', items: [] } })), post: vi.fn(), put: vi.fn() }; renderShell({ api, workspace: { landingDashboard: { id: 'D-1' }, availableDashboards: [{ id: 'D-1', name: 'State overview', relationship: 'SYSTEM' }] } }); expect(await screen.findByText('This dashboard has no reports yet.')).toBeInTheDocument(); expect(screen.queryByRole('searchbox')).not.toBeInTheDocument(); });
test('orders header utilities as notifications, settings, then account', () => { renderShell(); const utilities = within(screen.getByTestId('command-center-header-utilities')); expect(utilities.getAllByRole('button').map(button => button.getAttribute('aria-label'))).toEqual(['Notifications', 'Open settings', 'Open account menu']); });
test('keeps global search and support out of the command header', () => { renderShell(); expect(screen.queryByRole('searchbox')).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Support' })).not.toBeInTheDocument(); });
test('keeps specialist map and network tools out of the primary command rail', () => { renderShell(); expect(screen.queryByRole('button', { name: 'Map' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Network' })).not.toBeInTheDocument(); });
test('keeps Home local without invoking governed module navigation', () => { const onModuleNavigate = vi.fn(); renderShell({ onModuleNavigate }); fireEvent.click(screen.getByRole('button', { name: 'Home' })); expect(screen.getByRole('button', { name: 'Home' })).toHaveAttribute('aria-current', 'page'); expect(onModuleNavigate).not.toHaveBeenCalled(); });
test('keeps Dashboards local and opens its picker', () => { const onModuleNavigate = vi.fn(); const api = { get: vi.fn(async () => ({ data: { id: 'D-1', name: 'State overview', items: [] } })) }; renderShell({ api, workspace: { landingDashboard: { id: 'D-1' }, availableDashboards: [] }, onModuleNavigate }); fireEvent.click(screen.getByRole('button', { name: 'Dashboards' })); expect(screen.getByRole('button', { name: 'Dashboards' })).toHaveAttribute('aria-current', 'page'); expect(screen.getByRole('dialog', { name: 'Dashboards' })).toBeInTheDocument(); expect(onModuleNavigate).not.toHaveBeenCalled(); });
test.each([
  ['Intelligence', 'intelligence'], ['Utilities', 'utilities'], ['Alerts', 'alerts'],
  ['Reports', 'reports'],
])('routes governed %s through module navigation', (label, id) => { const onModuleNavigate = vi.fn(); renderShell({ onModuleNavigate }); fireEvent.click(screen.getByRole('button', { name: label })); expect(onModuleNavigate).toHaveBeenCalledWith(id); });
test('defines Utilities with the Lucide Boxes icon', () => { expect(commandCenterDestinations.find(destination => destination.id === 'utilities')).toMatchObject({ label: 'Utilities', icon: Boxes }); });
test('shows compact labels for command center navigation', () => { renderShell(); expect(screen.getByRole('button', { name: 'Home' })).toHaveTextContent('Home'); expect(screen.getByRole('button', { name: 'Dashboards' })).toHaveTextContent('Dashboards'); });
test('removes Team and switches only among authorized personas', () => { const onPersonaSelect = vi.fn(); renderShell({ personas: ['STATE_LEADERSHIP', 'CRIME_ANALYST'], onPersonaSelect }); expect(screen.queryByRole('button', { name: 'Team' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Open account menu' })); expect(screen.queryByRole('menuitem', { name: 'Station Operations' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('menuitem', { name: 'Crime Analyst' })); expect(onPersonaSelect).toHaveBeenCalledWith('CRIME_ANALYST'); expect(screen.queryByRole('menu', { name: 'Change persona' })).not.toBeInTheDocument(); });
test('ignores a removed persona without blanking the account menu', () => { const onPersonaSelect = vi.fn(); renderShell({ personas: ['REGIONAL_LEADERSHIP', 'STATE_LEADERSHIP'], onPersonaSelect }); fireEvent.click(screen.getByRole('button', { name: 'Open account menu' })); expect(screen.getByRole('menu', { name: 'Change persona' })).toBeInTheDocument(); expect(screen.queryByRole('menuitem', { name: 'Regional Leadership' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('menuitem', { name: 'State Leadership' })); expect(onPersonaSelect).toHaveBeenCalledWith('STATE_LEADERSHIP'); });
test('returns to all workspaces from the persona menu', () => { const onAllWorkspaces = vi.fn(); renderShell({ personas: [], onAllWorkspaces }); fireEvent.click(screen.getByRole('button', { name: 'Open account menu' })); fireEvent.click(screen.getByRole('menuitem', { name: 'All workspaces' })); expect(onAllWorkspaces).toHaveBeenCalledOnce(); });
test('persists appearance from Settings and closes the menu', () => { renderShell(); fireEvent.click(screen.getByRole('button', { name: 'Open settings' })); fireEvent.click(screen.getByRole('radio', { name: 'Dark' })); expect(screen.getByRole('application')).toHaveAttribute('data-appearance', 'dark'); expect(localStorage.getItem('ksp-command-center-appearance')).toBe('dark'); expect(screen.queryByRole('radiogroup', { name: 'Appearance' })).not.toBeInTheDocument(); });
test('keeps persona and settings menus mutually exclusive', () => { renderShell({ personas: ['CRIME_ANALYST'] }); fireEvent.click(screen.getByRole('button', { name: 'Open account menu' })); fireEvent.click(screen.getByRole('button', { name: 'Open settings' })); expect(screen.queryByRole('menu', { name: 'Change persona' })).not.toBeInTheDocument(); expect(screen.getByRole('radiogroup', { name: 'Appearance' })).toBeInTheDocument(); });
test('renders the full dashboard library in create mode', () => { renderShell({ api: { post: vi.fn() }, workspace: { availableDashboards: [] }, view: 'library', createMode: true }); expect(screen.getByRole('heading', { name: 'Dashboard Library' })).toBeInTheDocument(); expect(screen.getByRole('textbox', { name: 'Dashboard name' })).toBeInTheDocument(); });
